# Generated by Django 3.2.5 on 2021-07-25 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('date', models.DateTimeField()),
                ('status', models.TextField(default='sin procesar', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boro', models.TextField(max_length=50)),
                ('objectid', models.IntegerField(default=0, unique=True)),
                ('the_geom', models.TextField(max_length=250)),
                ('type', models.TextField(max_length=50)),
                ('provider', models.TextField(max_length=250)),
                ('name', models.TextField(max_length=250)),
                ('location', models.TextField(max_length=250)),
                ('lat', models.FloatField(default=0.0)),
                ('lon', models.FloatField(default=0.0)),
                ('x', models.FloatField(default=0.0)),
                ('y', models.FloatField(default=0.0)),
                ('location_t', models.TextField(max_length=250)),
                ('remarks', models.TextField(max_length=250)),
                ('city', models.TextField(max_length=50)),
                ('ssid', models.TextField(max_length=250)),
                ('sourceid', models.TextField(max_length=250)),
                ('activated', models.DateTimeField()),
                ('borocode', models.IntegerField(default=0)),
                ('boroname', models.TextField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archive', models.ManyToManyField(to='archives.Archive')),
            ],
        ),
    ]
