# Generated by Django 3.2.5 on 2021-07-25 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Archive',
            new_name='File',
        ),
        migrations.RemoveField(
            model_name='data',
            name='archive',
        ),
        migrations.AddField(
            model_name='data',
            name='file',
            field=models.ManyToManyField(to='archives.File'),
        ),
    ]
