# Generated by Django 3.2.5 on 2021-07-25 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_auto_20210725_0019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='file',
            new_name='files',
        ),
    ]
